project:
  name: "output"
  output_path: "./"

input:
  gpx_file: "Tag1.gpx"

search:
  radius_km: 5
  step_km: null   # wird automatisch berechnet (60% von radius_km)
  include:
    - "tourism=camp_site"
  exclude:
    - "tents=no"
    - "camp_site:tent=no"

map:
  zoom_start: 10
  track_color: "blue"
  marker_colors:
    near: "green"
    mid: "orange"
    far: "red"

overpass:
  retries: 5
  servers:
    - "https://overpass-api.de/api/interpreter"
    - "https://overpass.kumi.systems/api/interpreter"
    - "https://lz4.overpass-api.de/api/interpreter"

presets_file: "presets.yaml"
